name: Trigger Jenkins Build

on:
  push:
    branches:
      - master

jobs:
  trigger_jenkins_build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Jenkins CRUMB
        run: |
          CRUMB_RESPONSE=$(curl -s "https://jenkins.hanisntsolo.online/crumbIssuer/api/json" -u "hanisntsolo:11d5d4966d24071a4e3f052a037f55bd96")
          CRUMB=${CRUMB_RESPONSE#*\"crumb\":\"}
          CRUMB=${CRUMB%%\"*}
          echo "CRUMB=${CRUMB}" >> $GITHUB_ENV
        shell: bash

      - name: Trigger Jenkins Build
        env:
          JENKINS_USER: hanisntsolo
          JENKINS_TOKEN: 11ee3b80231ab8006fd67c5a9e93e014b6
        run: |
          curl -X POST "https://jenkins.hanisntsolo.online/job/sdetracker-be/build" \
            --user "${JENKINS_USER}:${JENKINS_TOKEN}" \
            -H "${CRUMB}"
