name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins_build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Jenkins CRUMB
        run: |
          CRUMB=$(curl -s "https://jenkins.hanisntsolo.online/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)" -u "hanisntsolo:$JENKINS_API_TOKEN")
          echo "CRUMB=${CRUMB}" >> $GITHUB_ENV
        shell: bash

      - name: Trigger Jenkins Build
        env:
          JENKINS_USER: hanisntsolo
          JENKINS_TOKEN: 11ee3b80231ab8006fd67c5a9e93e014b6
        run: |
          curl -X POST "https://jenkins.hanisntsolo.online/job/sdetracker-be/build" \
            --user "${JENKINS_USER}:${JENKINS_TOKEN}" \
            -H "${CRUMB}"
