name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins_build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Build
        run: |
          curl -X POST "https://jenkins.hanisntsolo.online/job/sdetracker-be/build" \
            --user hanisntsolo:11ee3b80231ab8006fd67c5a9e93e014b6
