name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins_build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Jenkins Crumb
        run: |
          CRUMB=$(curl -s "https://jenkins.hanisntsolo.online/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
          echo "JENKINS_CRUMB=${CRUMB}" >> $GITHUB_ENV

      - name: Trigger Jenkins Build
        env:
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          curl -X POST "https://jenkins.hanisntsolo.online/job/sdetracker-be/build" \
            --user hanisntsolo:${JENKINS_API_TOKEN} \
            -H "${JENKINS_CRUMB}"

            
