name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins_build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins Build
      env:
        CRUMB: ${{ secrets.JENKINS_CRUMB }}
      run: |
        curl -X POST "https://jenkins.hanisntsolo.online/job/sdetracker-be/build" \
          --user hanisntsolo:zaq12wsx \
          -H "$CRUMB"
